language: elixir
elixir: 1.11.2
otp_release: 23.1.2
sudo: false

addons:
  postgresql: 10

services:
  - redis-server

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

script:
  - mix ecto.create
  - mix ecto.migrate
  - mix run priv/repo/seeds.exs
  - mix run priv/repo/user_seeds.exs
  - mix run priv/repo/dev_seeds.exs
  - mix ecto.drop
  - mix ecto.create
  - mix test
